config/routes.rb
Rails.application.routes.draw do
  
  root to: redirect('/register/sign_up')
  # devise_for :users
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }


  get '/features/edit_pro_pic'
  post '/features/save_new_pro_pic'

  get '/logged_in', to: 'users/logged_in#index'
  # get '/register', to: 'devise/registrations#new'
  # these routes can be rewritten as collection below
  resources :surveys, only: [:new, :create, :edit, :update]
  get '/surveys/stats', to: 'surveys#stats'
  get '/surveys/stats_survey', to: 'surveys#stats_survey'
  get '/surveys/thanks', to: 'surveys#thanks'
  get '/surveys/:link', to: 'surveys#attend'
  post '/surveys/submit', to: 'surveys#submit'
  post '/surveys/invite', to: 'surveys#invite'
  delete '/surveys/delete', to: 'surveys#delete'
  get '/register', to: redirect('/register/sign_up')
  # put '/surveys/update', to: 'surveys#update'
  #rewritten

  # resources :surveys, only: [:new, :create, :update, :edit] do
  #   collection do
  #     get 'stats'
  #     get 'thanks'
  #     post 'submit'
  #     post 'invite'
  #   end
  # end
  #   get '*all', to: 'users/logged_in#index', 
  match '*path', to: redirect('/404'), via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :surveys
  has_one_attached :avatar

  # validate :password_complexity

  # def password_complexity
  #   if password.present? and not password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d). /)
  #     errors.add :password, "must include at least one lowercase letter, one uppercase letter, and one digit"
  #   end
  # end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/logged_in_controller.rb
class Users::LoggedInController < ApplicationController

  before_action :authenticate_user!
  def index
    @surveys = current_user.surveys.paginate(page: params[:page], per_page: 5)
  end

  def new

  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/logged_in/_invite_mailer_modal.html.erb
<div class="modal fade" id=<%=survey_link%> tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Invite By Email</h5>
        <h6 class="modal-title"><%=survey_title%><h6>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with url: surveys_invite_path do |form| %>
          <div class="form-group d-inline-block">
            <%= form.text_field :invitee, placeholder:"Name",class:"form-control", required:true, autofocus:true %>
          </div>
          <div class="form-group d-inline-block">
            <%= form.text_field :email, placeholder:"Email",class:"form-control", required:true, autofocus:true %>
            <%= form.hidden_field :inviter, value: inviter   %>
            <%= form.hidden_field :link, value: survey_link %>
          </div>
          <div class="form-group d-inline-block">
            <%= form.submit "send mail", class: "btn btn-primary close-modal-submit"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/logged_in/_modal.html.erb
<div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Delete Survey</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Do you really want to delete this survey?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="delete">Delete</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/users/logged_in/_question_fields.html.erb
<%= survey_form.fields_for :questions do |question_form| %>
  <%= question_form.text_field :question %>
  <%= question_form.link_to_remove "Remove this question" %>
<%end%>

app/views/users/logged_in/index.html.erb
 <%if current_user.isadmin?%>
  <%= render 'layouts/add_survey_button' %>
  <%if @surveys.length != 0 %>
      <span id = "page_no" value="<%=@surveys.current_page %>"></span>
      <span id = "total_pages" value="<%= @surveys.total_pages %>"></span>
      <span id = "record_in_current_page" value="<%= @surveys.length %>" ></span>

      <div class="survey-share-stats-table">
        <h3 style="text-align: center;margin-top: 8px; font-family: cursive;">Your Surveys </h3>
        <div class="d-flex justify-content-center">

          <table class="table front-table table-hover p-3">
          <thead class="m-3 p-3"><tr> <th>Title</th> <th>Link</th> <th class="middle-front-table">Report</th> <th class="middle-front-table">Invite</th> <th class="font-table-delete">Delete</th>  <th class="middle-front-table">Stats</th><th class="middle-front-table">Edit</th></tr></thead>
          <tbody class="m-3 p-3">
            <% @surveys.each do |survey| %>
              <tr id="survey_table_<%=survey.link%>" class="p-3">
                <td width="10%"><%=survey.title %></td>  <td class="link-copied-shared"><input  onclick="copyLink(this)" class="copy-link" value = "<%=root_url%>surveys/<%=survey.link%>"></input> </td><!-- <%= button_to "stats", { :controller => "/surveys", :action => "stats", link: survey.link}, {:method=>:get} %>  -->
                  <!-- <%= link_to "stats", surveys_stats_path(link: survey.link), remote: :true, :class => "button" %> -->
                <td class="middle-front-table"><%= link_to surveys_stats_path(link: survey.link, format: 'csv' ) do %><i class="fa fa-download" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Download CSV"></i><%end%></td>
                <td class="middle-front-table">
                <span id="new_category " data-toggle="modal" data-target="#<%=survey.link%>">
                  <span class="invite"><i class="fas fa-paper-plane" data-toggle="tooltip" data-placement="top" title="Send Email" ></i></span>
                </span>
                </td>
                <td class="font-table-delete">
                  <span class="delete-survey-button" data-survey-link="<%=survey.link%>">
                    <i class='fa fa-trash' aria-hidden='true' data-toggle="tooltip" data-placement="top" title="Delete Survey"></i>
                  </span>
                </td>

                <td class="middle-front-table">
                  <%= link_to surveys_stats_survey_url(link: survey.link), method: :get do%>
                    <i class="fa fa-bar-chart" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Get Responses"></i>
                  <% end %>
                </td>

                <td class="middle-front-table">
                  <%= link_to edit_survey_url(survey) , method: :get do%>
                    <i class="fa fa-pencil" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Edit the survey"></i>
                  <% end %>
                </td>


                <%= render :partial => 'invite_mailer_modal', locals: {survey_link: survey.link, survey_title: survey.title, inviter: current_user.firstname} %>
              </tr>
            <%end%>
          </tbody>
          </table>

          <div class="digg_pagination">
            <%= will_paginate @surveys, renderer: BootstrapPagination::Rails %>
          </div>
    <%= render 'modal'%>
  <%end%>
<%end%>