config/routes.rb
Rails.application.routes.draw do
  
  root to: redirect('/register/sign_up')
  # devise_for :users
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }


  get '/features/edit_pro_pic'
  post '/features/save_new_pro_pic'

  get '/logged_in', to: 'users/logged_in#index'
  # get '/register', to: 'devise/registrations#new'
  # these routes can be rewritten as collection below
  resources :surveys, only: [:new, :create, :edit, :update]
  get '/surveys/stats', to: 'surveys#stats'
  get '/surveys/stats_survey', to: 'surveys#stats_survey'
  get '/surveys/thanks', to: 'surveys#thanks'
  get '/surveys/:link', to: 'surveys#attend'
  post '/surveys/submit', to: 'surveys#submit'
  post '/surveys/invite', to: 'surveys#invite'
  delete '/surveys/delete', to: 'surveys#delete'
  get '/register', to: redirect('/register/sign_up')
  # put '/surveys/update', to: 'surveys#update'
  #rewritten

  # resources :surveys, only: [:new, :create, :update, :edit] do
  #   collection do
  #     get 'stats'
  #     get 'thanks'
  #     post 'submit'
  #     post 'invite'
  #   end
  # end
  #   get '*all', to: 'users/logged_in#index', 
  match '*path', to: redirect('/404'), via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :question_options, :through => :questions
  has_many :attempts
  accepts_nested_attributes_for :questions, :allow_destroy => true
  accepts_nested_attributes_for :question_options, :allow_destroy => true

  validates :link, presence: true
  validates :link, uniqueness: true
  before_validation :generate_token, on: :create

  # self.primary_key = 'link'

  def generate_token
    begin
      self.link = SecureRandom.urlsafe_base64(64, false)
    end while self.class.find_by(link: link)
  end

  def to_param
    link
  end

  def title=(title)
    if title == ''
      write_attribute(:title, 'Untitled form')
    else
      write_attribute(:title, title)
    end
  end

  def self.format_question(question_array, survey_id, attempt_id, current_user)
    answers = Array.new()
    user_id = current_user.id if current_user
    question_array.each do |key, value|
      answers.push({question_id: value[:question_id], survey_id: survey_id, attempt_id: attempt_id, answer: value[:answer_text], user_id: user_id})
    end
    answers
  end

end

app/controllers/surveys_controller.rb
require 'csv'
require 'will_paginate/array'
# survey controller
class SurveysController < ApplicationController
  before_action :permit_survey_answer, only: [:create]
  before_action :permit_answer_array, only: [:submit]
  before_action :permit_update_params, only: [:update]
  before_action :authenticate_user!, except: %i[attend submit thanks]
  before_action :find_survey, only: [:attend, :edit, :update, :stats]
  after_action  :redirect_after_survey_submit, only: [:submit]
  before_action :check_question_presence, only: [:submit]

  def create
    current_user.surveys.create(params[:survey])
    redirect_to logged_in_url
  end

  def new; end

  def attend; end

  def edit; end

  def update
    @survey.update(params[:survey])
    redirect_to logged_in_url
  end

  def submit
    attempt_id = Attempt.create(survey_id: params[:survey_id]).id
    answers = Answer.format_question(params[:question_array], params[:survey_id],
                                     params[:user_name], attempt_id, current_user)
    Answer.create(answers)
    #answer = Answer.save(answers)
    #if answer.save
    # unless current_user
    #   redirect_to surveys_thanks_url
    # else
    #   redirect_to logged_in_url
    # end
    # #end
  end

  def thanks; end

  def invite
    UserMailer.with(invitee: params[:invitee], invitor: params[:inviter], email: params[:email], link: params[:link]).invite_email.deliver_now
  end

  def stats
    respond_to do |format|
      format.csv { send_csv(Answer.generate_csv(params[:link])) }
    end
  end

  def stats_survey
    @array = Answer.generates_stats(params[:link])
    if @array.length == 1
      flash[:error] = 'Entries not found.'
      redirect_to '/logged_in'
    end
  end

  def delete
    render json: { msg: 'destroyed' } if Survey.find_by_link(params[:link]).destroy
  end

  private

  def permit_answer_array
    # params.permit(:survey_id, question_array: [:question_id, :answer_text])
    params.permit!
  end

  def permit_survey_answer
    # params.permit(survey: [:title, :description, :questions_attributes])
    params.permit!
  end

  def permit_update_params
    params.permit!
    #params.permit(:survey, :id)
  end

  def send_csv(csv)
    send_data(csv,
              type: 'text/csv; charset=utf-8; header=present',
              disposition: "attachment; filename=#{@survey.title}_survey_data.csv")
  end

  def find_survey
    link = params[:link] || params[:id]
    @survey = Survey.find_by_link(link)
    # flash.keep
    # redirect_to root_url, flash: { notice: "Record not found." } if @survey.nil?
    if @survey.nil?
      flash[:error] = 'No such survey.'
      if current_user
        redirect_to '/logged_in'
      else
        redirect_to root_url
      end
    end
  end

  def redirect_after_survey_submit
    flash[:notice] = 'Successfully completed survey.'
    redirect_to current_user ? logged_in_path : survey_thanks
  end

  def check_question_presence
    if params[:question_array].nil?
      flash[:error] = 'No question to submit'
      if current_user
        redirect_to '/logged_in'
      else
        redirect_to root_url
      end
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/attend.html.erb
<div class = "title"><%= @survey.title%></div>
<div class = "form-orientation"><%= @survey.description%></div>

<form>

<div class="form-orientation question-box">
  <input type="hidden" name="survey" value="<%=@survey.id%>">
  Name: <input type="text" name="username" class="response-submit-name" required>
  <ul>
  <%@survey.questions.each do |question|%>
    <%input_type = question.question_type%>
    <div class="question-answer">

    <li><div class = "question-holder"><span class="question"><b><%= question.question%></b></span></div>
      <div class="answer">
          <ul>
          <% if input_type == "text" %>
            <li><textarea id="answer_for_question_<%question.id%>"  rows="4" cols="50" name=<%=question.id%> ></textarea>
          <%elsif input_type == "drop_down"%>
            <li><select name="<%=question.id%>" >
              <%question.question_options.each do |option|%>
                <option><%=option.option %></option>
              <%end%>
            </select>
          <%else%>
              <%question.question_options.each do |option|%>
                <input type="<%=input_type%>" name=<%=question.id%> value="<%=option.option%>"> <%=option.option%><br>
              <%end%>
          <%end%>
          </ul>
      </div>
    </div>
  <%end%>
  </ul>
</div>

<button type='button' class='save-response-button btn btn-primary form-orientation margin-bottom-50'>submit response</button>

</form>

app/views/surveys/create.html.erb
<h1>Surveys#create</h1>
<p>Find me in app/views/surveys/create.html.erb</p>

app/views/surveys/edit.html.erb
<%
=begin%>
 <%= form_with url: survey_path(@survey),  method: :put do %> 
<%
=end%>

<div id="form-edit">

<%= nested_form_for @survey do |survey_form| %>
  <div class = "title"><%= survey_form.text_field :title %></div>

<div class = "form-orientation"><%= survey_form.text_field :description%></div>

<div class="form-orientation question-box">
  <div class="confirmed_question_div">  
    <ul>
        <%= survey_form.fields_for :questions do |question| %>
          <li> <%= question.text_field :question %>
          <%= question.link_to_remove "remove" %>
          <span>question_type: <%= question.select :question_type, options_for_select([ "select type" ,"text", "radio", "drop_down", "checkbox"],selected: question.object.question_type, disabled: "select type" ),
                                 {},{:class => "change_type" ,  data: {"question-id": question.object.id} } %>
          <div id="changed_answer_for_question_<%=question.object.id%>" >
            <ul>
              <%= question.fields_for :question_options do |option| %>
                <li><%= option.text_field :option %>
                <%= option.link_to_remove "remove" %>
              <%end%>
              <p><%= question.link_to_add "Add option", :question_options %></p>
            </ul>
          </div>
        <%end%>
        <p><%= survey_form.link_to_add "Add question", :questions %></p>
    </ul>
  </div>
</div>

<%= submit_tag "Save changes", class:"btn btn-primary form-orientation margin-bottom-50" %>
<% end %>

</div>

app/views/surveys/new.html.erb
<div class ="form_div margin-bottom-50">

<input placeholder="Untitled form" id="survey-title" class="title survey_input"> </input> <br>

<input placeholder="Form description" id="form-description" class="form-orientation survey_input"></input>

<div class="form-orientation confirmed-question-box"></div>

<div class="form-orientation question-box" id="question-box">
  <div class="question-holder" data-question-no="">
    <input class="question survey_input" id="question" placeholder="Type your question here"></input>
    <div class="question-type">
      <div class="question-type-header type-header">
        <label>Type of Question</label>
      </div>
      <div class="type-header">
        <select name="question_type" id="question_type" class="question_type_selection">
          <option disabled selected value> -- select an option -- </option>
          <option value="radio">Radio button</option>
          <option value="drop_down">Dropdown</option>
          <option value="checkbox">Check box</option>
          <option value="text">Text</option>
        </select>
      </div>
      </div>
    </div>
    <div class="Answer_Options"></div>
  </div>
</div>

</div>

app/views/surveys/stats.js.erb
$('.survey-share-stats-table').empty().show();

app/views/surveys/stats_survey.html.erb
<h3 style="text-align: center;margin-top: 8px; font-family: cursive;">Entries </h3>

<table class="table front-table table-hover p-3">
    <thead>
        <%@array.first.each do |row|%>
            <th><%=row%></th>
        <%end%>
    </thead>
    <tbody class="m-3 p-3">
        <%@array.slice(1..-1).each do |row|%>
            <tr>
                <%row.each do |col|%>
                    <td><%=col%></td>
                <%end%>
            </tr>
        <%end%>
    </tbody>
</table>

app/views/surveys/thanks.html.erb
<div class="d-flex justify-content-center p-3 m-3">
  <div class="col-sm-6 p-3 m-3"> Thankyou For Attending The Survey </div>
</div>