config/routes.rb
Rails.application.routes.draw do
  
  root to: redirect('/register/sign_up')
  # devise_for :users
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }


  get '/features/edit_pro_pic'
  post '/features/save_new_pro_pic'

  get '/logged_in', to: 'users/logged_in#index'
  # get '/register', to: 'devise/registrations#new'
  # these routes can be rewritten as collection below
  resources :surveys, only: [:new, :create, :edit, :update]
  get '/surveys/stats', to: 'surveys#stats'
  get '/surveys/stats_survey', to: 'surveys#stats_survey'
  get '/surveys/thanks', to: 'surveys#thanks'
  get '/surveys/:link', to: 'surveys#attend'
  post '/surveys/submit', to: 'surveys#submit'
  post '/surveys/invite', to: 'surveys#invite'
  delete '/surveys/delete', to: 'surveys#delete'
  get '/register', to: redirect('/register/sign_up')
  # put '/surveys/update', to: 'surveys#update'
  #rewritten

  # resources :surveys, only: [:new, :create, :update, :edit] do
  #   collection do
  #     get 'stats'
  #     get 'thanks'
  #     post 'submit'
  #     post 'invite'
  #   end
  # end
  #   get '*all', to: 'users/logged_in#index', 
  match '*path', to: redirect('/404'), via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  
end

app/views/layouts/_add_survey_button.html.erb
<%= button_to new_survey_url, method: :get,class: "button_plus" do%>
  <i class="fas fa-plus size-plus-button"></i>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">

  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="https://www.qburst.com/"> Qburst Technologies</a>
  </div>
  
</footer>

app/views/layouts/_login_header.html.erb
<div class="login-div">
  <nav class="nav-style-row">
    <div class="container">
      <%= form_for(:user, :url => session_path(:user), :html => {:class => "form-row"} ) do |f| %>
          <div class="col">
            <%= f.text_field :email, placeholder: "Email", class: "form-control form_container font-fb-copy" %>
          </div>
          <div class="col">
            <%= f.password_field :password, placeholder: "Password", class: "form-control form_container font-fb-copy" %>
            <%= link_to "Forgot your password?", new_password_path(:user), class: "font-fb-copy forgot-password" %>
          </div>
          <span class="d-inline-block">
            <%= f.submit 'Sign in',class: "btn btn-primary btn-sm" %>
          </span>
      <%end%>
    </div>
  </nav>
</div>

app/views/layouts/_logout_header.html.erb
<div class="container">
    <a href='/logged_in'> <i class="fa fa-home fa-3x home-button" aria-hidden="true">  </i> </a>
    <% if current_user.avatar.attached? %>
        <a href="<%=features_edit_pro_pic_url %>"> <%=image_tag (current_user.avatar), :title => current_user.firstname, :class => "style-pro-pic"%></a> 
    <%else%>
        <a href="<%=features_edit_pro_pic_url %>"><img src="<%= asset_path( 'image.jpg' ) %>" class="style-pro-pic"/></a>   
    <%end%> 
    <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "Logout-button btn-primary btn-sm", "data-toggle" => "tooltip", "data-placement" => "top", "title" => "Log out" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSurveyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>

    <header class="navbar navbar-fixed-top dark-black-color nav-style">
      <div class="col-sm-12 main-header-div">
          <%
=begin%>
 <img src="<%= asset_path( 'survey_app_logo.png' ) %>" class="Title-style"/> 
<%
=end%>
          <%if user_signed_in? %>
              <%= render 'layouts/logout_header'%>
          <%else%>
            <%= render 'layouts/login_header' %>
          <%end%>
      </div>
    </header>
      <% if flash[:notice] %>
          <div class="notification is-primary global-notification">
            <p class="notice alert-success d-flex justify-content-center"><%= flash[:notice] %></p>
          </div>
      <% end %>

      <% if flash[:error] %>
        <div class="notification is-primary global-notification">
          <p class="alert alert-danger d-flex justify-content-center"><%= flash[:error] %></p>
        </div>
      <% end %>

      <%= yield %>
    </main>
    
</body>
<%= render 'layouts/footer' %>

</html>